apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # The git commit hash (sha) identifying your latest release candidate
  - github.com/spring-framework-books/cloud-native-spring-in-action-PolarBookshop/catalog-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: catalog-config

images:
  - name: catalog-service
    newName: ghcr.io/spring-framework-books/catalog-service
    newTag: latest

replicas:
  - count: 2
    name: catalog-service
