# Build
custom_build(
    # Name of the container image
    ref = 'catalog-service',
    # Command to build the container image
    # On Windows, replace $EXPECTED_REF with %EXPECTED_REF%
    command = './mvnw spring-boot:build-image -DimageName=$EXPECTED_REF',
    # Files to watch that trigger a new build
    deps = ['pom.xml', './target/classes'],
    live_update = [
        sync('./target/classes', '/workspace/BOOT-INF/classes')
  ]
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('catalog-service', port_forwards=['9001'])