apiVersion: v1
kind: Service
metadata:
  # The name of the Service; it must be a valid DNS name.
  name: order-service
  labels:
    app: order-service
spec:
  # The type of Service
  type: ClusterIP
  selector:
    #The label used to match the Pods to target and expose
    app: order-service
  ports:
    - protocol: TCP
      #The port exposed by the Service
      port: 80
      # The port exposed by the Pods targeted by the Service
      targetPort: 9002