apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uses the manifests in your Catalog Service repo on GitHub as the base for further customizations
  - github.com/polarbookshop/catalog-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: catalog-config

images:
  - name: catalog-service
    newName: ghcr.io/spring-framework-books/catalog-service
    newTag: latest

replicas:
  - name: catalog-service
    count: 2