name: Acceptance Stage
on:
  workflow_run:
    # This workflow is triggered when the Commit Stage workflow completes a run.
    workflows: ['Commit Stage']
    types: [completed]
    # This workflow runs only on the main branch.
    branches: main
# Ensures that only one workflow runs at a time
concurrency: acceptance

env:
  OWNER: ${{ github.repository_owner }} 
  REGISTRY: ghcr.io
  #APP_REPO: catalog-service
  DEPLOY_REPO: cloud-native-spring-in-action-PolarBookshop
  VERSION: ${{ github.sha }}
# this job runs only if the commit stage completed successfully
jobs:
  functional:
    name: Functional Acceptance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        project: [
          config-service,
          edge-service,
          catalog-service,
          order-service,
          dispatcher-service
        ]
    steps:
      - run: echo "Running functional acceptance tests"
  performance:
    name: Performance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        project: [
          config-service,
          edge-service,
          catalog-service,
          order-service,
          dispatcher-service
        ]
    steps:
      - run: echo "Running performance tests"
  security:
    name: Security Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        project: [
          config-service,
          edge-service,
          catalog-service,
          order-service,
          dispatcher-service
        ] 
    steps:
      - run: echo "Running security tests"
  deliver:
    name: Deliver release candidate to production
    needs: [ functional, performance, security ]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        project: [
          config-service,
          edge-service,
          catalog-service,
          order-service,
          dispatcher-service
        ]
    steps:
      # - name: Log into container registry
      #   uses: docker/login-action@v2 
      #   with:
      #     registry: ${{ env.REGISTRY }} 
      #     username: ${{ github.repository_owner }} 
      #     password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Dump GitHub context
        env:
            app_image: "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.project }}"
            app_name: "${{ matrix.project }}"
            app_version: "${{ env.VERSION }}"
        run: |
          echo "App image: $app_image"
          echo "App name: $app_name"
          echo "App version: $app_version"
      - name: Deliver application to production
        # An action to send an event to another repository and trigger a workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ env.DEPLOY_REPO }}
          # A name to identify the event (this is up to you)
          event-type: app_delivery
          # The payload of the message sent to the other repository. Add any information that the other repository might need to perform its operations.
          client-payload: '{
            "app_image": "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.project }}",
            "app_name": "${{ matrix.project }}",
            "app_version": "${{ env.VERSION }}"}'
